comment:
  image:
    repository: darkonone/comment
    tag: logging
  service:
    externalPort: 9292

post:
  image:
    repository: darkonone/post
    tag: logging
  service:
    externalPort: 5000

ui:
  image:
    repository: darkonone/ui
    tag: logging
  service:
    externalPort: 9292
