---
roles:
  # Install a role from Ansible Galaxy.
  - src: geerlingguy.docker
    version: 4.1.0
  - src: geerlingguy.kubernetes
    version: 7.1.0

collections:
  # Install a collection from Ansible Galaxy.
