{{- if (eq .Values.provider "yc") }}
kind: StorageClass
apiVersion: {{ if .Capabilities.APIVersions.Has "storage.k8s.io/v1" }}storage.k8s.io/v1{{ else }}storage.k8s.io/v1beta1{{ end }}
metadata:
  name: {{ template "fullname" . }}-fast
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    kubernetes.io/cluster-service: "true"
{{- if eq .Values.provider "yc" }}
provisioner: disk-csi-driver.mks.ycloud.io
parameters:
  type: network-ssd
  csi.storage.k8s.io/fstype: ext4
{{- end }}
{{- end }}
